- name: Update authorized key
  hosts: k8s_cluster
  remote_user: ansible

  tasks:
    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: ansible
        state: ansible
        key: "{{ lookup('file', '/home/netwon/.ssh/ansible.pub') }}"
