- name: Update authorized key
  hosts: k8s_cluster
  remote_user: vagrant

  tasks:
  - name: Set authorized key taken from file
    ansible.posix.authorized_key:
      user: vagrant
      state: present
      key: "{{ lookup('file', '/home/netwon/.ssh/ansible.pub') }}"