- name: Disable password based authentication
  hosts: k8s_cluster
  remote_user: vagrant
  become: true

  tasks:
  - name: disable ssh key auth
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: ^PasswordAuthentication
      line: PasswordAuthentication no
    notify:
      restart ssh

  handlers:
  - name: restart ssh
    service:
      name: sshd
      state: restarted