- name: k8s cluster setup
  hosts: k8s_cluster

  tasks:
    - name: Execute the script file that will install all the k8s related dependency
      ansible.builtin.script: ./file/install-k8s.sh
      args:
          executable: /bin/bash
