---
- name: Configure server to make it k8s cluster
  hosts: k8s_cluster
  become: yes

  tasks:
    - name: Copy change hostname script file to all the remote machine
      ansible.builtin.copy:
        src: ./file/change-hostname.sh
        dest: /home/vagrant/k8s-setup
        owner: vagrant
        mode: "0744"

    - name: Run hostname change script
      ansible.builtin.shell:
        chdir: /home/vagrant/k8s-setup
        cmd: sudo ./change-hostname.sh {{ inventory_hostname }}
      args:
        executable: /bin/bash

    - name: Disable CRI plugin in all machine
      ansible.builtin.lineinfile:
        path: /etc/containerd/config.toml
        regexp: "^disabled_plugins="
        line: "# disabled_plugins= ['cri']"
        backup: true
      notify:
        - Restart containerd

    - name: Disable swap in all machine
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: "^(\/dev\/mapper\/vgvagrant-swap_1)"
        backup: true
        line: "# /dev/mapper/vgvagrant-swap_1"

  handlers:
    - name: Restart containerd
      ansible.builtin.service:
        name: containerd
        state: restarted
