---
- name: Configure server to make it k8s cluster
  hosts: k8s_cluster

  tasks:
  - name: Change hostname of each server
    ansible.builtin.copy:
      src: ./file/change-hostname.sh
      dest: /home/vagrant/k8s-setup
      owner: vagrant
      mode: "0744"
  
  - name: Execute hostname change script
    ansible.builtin.shell:
      chdir: /home/vagrant/k8s-setup
      cmd: sudo ./change-hostname.sh {{ inventory_hostname }}
    args:
      executable: /bin/bash
